### PR TITLE
Fix rounded title bar on maximized window

### PR DESCRIPTION
**Pull request by gabelluardo**
Related to  #104

### CODE REVIEW

**Comment by gabelluardo** [comment]
Oh right, can you please tell me which files I have to modify? I guess the xml files in the `ui` folder

**Comment by p0ryae** [comment]
Tested this PR and I'd like to confirm it does fix the issue following with a system restart after compilation and installation.

**Comment by kupiqu** [comment]
> Oh right, can you please tell me which files I have to modify? I guess the xml files in the `ui` folder

If I don't forget anything:

1. `breezesettingsdata.kcfg` to set the default value (please keep current behavior as default)
2. `breezeconfigurationui.ui` for adding the option to the settings
3. `breezeconfigwidget.cpp` to manage the change in settings

**Comment by gabelluardo** [comment]
This is the modified configuration window:
immagine

@kupiqu I disabled the option for me, but as you said the current behavior is the default

**Comment by kupiqu** [comment]
Hi @gabelluardo ,

Sorry I had to reverse the pull request due to conflicts with current master version. Could you please request a new pull on top of current master or V1.3.3? Thanks!

**Pull request merged**
