### PR TITLE
Change corner radius to 5.

### PR DESCRIPTION
**Pull request by Luwx**
This way the decoration becomes compatible with the rounding value of shapecorners effect.

### CODE REVIEW

**Comment by kupiqu** [comment]
Sorry but I won't hard code changes that deviate from the Breeze style in the opposite direction of what I like... But likes are in the eyes, so why don't you create a feature request issue to be able to adjust that property in settings?

**Comment by Luwx** [comment]
Nah.. I don't want to clutter your settings page and code for such a small change.

**Comment by kupiqu** [comment]
> Nah.. I don't want to clutter your settings page and code for such a small change.

I still think it would be a nice feature for users like you preferring the shapecorners effect, as well as for those liking totally flat behavior, while being able to keep the very same breeze default.

**Comment by kupiqu** [comment]
Done

**Pull request closed without merging**
