### PR TITLE
Port to Plasma 6

### PR DESCRIPTION
**Pull request by chiyuki0325**
This is an attempt to port this great window decoration to Plasma 6.

P.S. I do not use other Linux distributions, so the dependency section in the README has not been modified.

### CODE REVIEW

**Comment by OzzyHelix** [comment]
I can confirm that building their branch works but with some errors it took a couple tries to get it to compile this is the terminal output that contains the errors 
```
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp: In lambda function:
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp:66:98: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
   66 |         connect( m_ui.gradientOverrideLabelSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), [=](int /*i*/){updateChanged();} );
      |                                                                                                  ^
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp:66:98: note: add explicit ‘this’ or ‘*this’ capture
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp: In lambda function:
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp:69:97: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
   69 |         connect( m_ui.opacityOverrideLabelSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), [=](int /*i*/){updateChanged();} );
      |                                                                                                 ^
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp:69:97: note: add explicit ‘this’ or ‘*this’ capture
make[1]: *** [CMakeFiles/Makefile2:667: config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp: In lambda function:
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp:51:83: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
   51 |         connect( m_ui.buttonSpacing, QOverload<int>::of(&QSpinBox::valueChanged), [=](int /*i*/){updateChanged();} );
      |                                                                                   ^
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp:51:83: note: add explicit ‘this’ or ‘*this’ capture
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp: In lambda function:
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp:55:89: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
   55 |         connect( m_ui.cornerRadiusSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), [=](int /*i*/){updateChanged();} );
      |                                                                                         ^
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp:55:89: note: add explicit ‘this’ or ‘*this’ capture
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp: In lambda function:
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp:61:84: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
   61 |         connect( m_ui.opacitySpinBox, QOverload<int>::of(&QSpinBox::valueChanged), [=](int /*i*/){updateChanged();} );
      |                                                                                    ^
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp:61:84: note: add explicit ‘this’ or ‘*this’ capture
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp: In lambda function:
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp:62:85: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
   62 |         connect( m_ui.gradientSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), [=](int /*i*/){updateChanged();} );
      |                                                                                     ^
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeconfigwidget.cpp:62:85: note: add explicit ‘this’ or ‘*this’ capture
/home/ozzy/Documents/development/SierraBreezeEnhanced/breezedecoration.cpp: In member function ‘virtual void Breeze::Decoration::hoverMoveEvent(QHoverEvent*)’:
/home/ozzy/Documents/development/SierraBreezeEnhanced/breezedecoration.cpp:358:86: warning: ‘QPointF QHoverEvent::posF() const’ is deprecated: Use position() [-Wdeprecated-declarations]
  358 |             const bool groupContains = m_leftButtons->geometry().contains(event->posF()) || m_rightButtons->geometry().contains(event->posF());
      |                                                                           ~~~~~~~~~~~^~
In file included from /usr/include/qt6/QtGui/QMouseEvent:1,
                 from /home/ozzy/Documents/development/SierraBreezeEnhanced/breezesizegrip.h:26,
                 from /home/ozzy/Documents/development/SierraBreezeEnhanced/breezedecoration.cpp:31:
/usr/include/qt6/QtGui/qevent.h:265:20: note: declared here
  265 |     inline QPointF posF() const { return position(); }
      |                    ^~~~
/home/ozzy/Documents/development/SierraBreezeEnhanced/breezedecoration.cpp:358:140: warning: ‘QPointF QHoverEvent::posF() const’ is deprecated: Use position() [-Wdeprecated-declarations]
  358 |             const bool groupContains = m_leftButtons->geometry().contains(event->posF()) || m_rightButtons->geometry().contains(event->posF());
      |                                                                                                                                 ~~~~~~~~~~~^~
/usr/include/qt6/QtGui/qevent.h:265:20: note: declared here
  265 |     inline QPointF posF() const { return position(); }
      |                    ^~~~
[ 93%] Linking CXX shared module bin/sierrabreezeenhanced.so
[ 95%] Built target sierrabreezeenhanced
make: *** [Makefile:136: all] Error 2
❯ make -j24
[  0%] Built target sierrabreezeenhancedcommon6_autogen_timestamp_deps
[  0%] Built target sierrabreezeenhanced-kcm-desktop-gen
[  0%] Built target kcm_sierrabreezeenhanceddecoration-kcm-desktop-gen
[  2%] Built target sierrabreezeenhancedcommon6_autogen
[  2%] Built target kcm_sierrabreezeenhanceddecoration_autogen_timestamp_deps
[ 11%] Built target sierrabreezeenhancedcommon6
[ 13%] Built target kcm_sierrabreezeenhanceddecoration_autogen
[ 13%] Built target sierrabreezeenhanced_autogen_timestamp_deps
[ 16%] Building CXX object config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/kcm_sierrabreezeenhanceddecoration_autogen/mocs_compilation.cpp.o
[ 18%] Building CXX object config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/breezedetectwidget.cpp.o
[ 20%] Building CXX object config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/breezeexceptiondialog.cpp.o
[ 23%] Built target sierrabreezeenhanced_autogen
[ 69%] Built target sierrabreezeenhanced
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp: In lambda function:
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp:66:98: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
   66 |         connect( m_ui.gradientOverrideLabelSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), [=](int /*i*/){updateChanged();} );
      |                                                                                                  ^
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp:66:98: note: add explicit ‘this’ or ‘*this’ capture
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp: In lambda function:
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp:69:97: warning: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Wdeprecated]
   69 |         connect( m_ui.opacityOverrideLabelSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), [=](int /*i*/){updateChanged();} );
      |                                                                                                 ^
/home/ozzy/Documents/development/SierraBreezeEnhanced/config/breezeexceptiondialog.cpp:69:97: note: add explicit ‘this’ or ‘*this’ capture
[ 72%] Linking CXX shared module ../bin/org.kde.kdecoration2.kcm/kcm_sierrabreezeenhanceddecoration.so
[100%] Built target kcm_sierrabreezeenhanceddecoration
❯ sudo make install
[  0%] Built target sierrabreezeenhancedcommon6_autogen_timestamp_deps
[  2%] Built target sierrabreezeenhancedcommon6_autogen
[ 11%] Built target sierrabreezeenhancedcommon6
[ 11%] Built target sierrabreezeenhanced-kcm-desktop-gen
[ 11%] Built target sierrabreezeenhanced_autogen_timestamp_deps
[ 13%] Built target sierrabreezeenhanced_autogen
[ 60%] Built target sierrabreezeenhanced
[ 60%] Built target kcm_sierrabreezeenhanceddecoration-kcm-desktop-gen
[ 60%] Built target kcm_sierrabreezeenhanceddecoration_autogen_timestamp_deps
[ 62%] Built target kcm_sierrabreezeenhanceddecoration_autogen
[100%] Built target kcm_sierrabreezeenhanceddecoration
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib/qt6/plugins/org.kde.kdecoration2/sierrabreezeenhanced.so
-- Set non-toolchain portion of runtime path of "/usr/lib/qt6/plugins/org.kde.kdecoration2/sierrabreezeenhanced.so" to ""
-- Installing: /usr/share/applications/sierrabreezeenhanced.desktop
-- Installing: /usr/lib/libsierrabreezeenhancedcommon6.so.1.3.3
-- Installing: /usr/lib/libsierrabreezeenhancedcommon6.so.0
-- Installing: /usr/lib/qt6/plugins/org.kde.kdecoration2.kcm/kcm_sierrabreezeenhanceddecoration.so
-- Installing: /usr/share/applications/kcm_sierrabreezeenhanceddecoration.desktop
```

**Comment by kupiqu** [comment]
Hi, 

I also see some error at first compilation:


```
In file included from /home/jsardid/Documents/al3/sbe6/config/breezedetectwidget.cpp:30:
/home/jsardid/Documents/al3/sbe6/config/breezedetectwidget.h:34:10: fatal error: ui_breezedetectwidget.h: El fitxer o directori no existeix
   34 | #include "ui_breezedetectwidget.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/build.make:159: config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/breezedetectwidget.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/jsardid/Documents/al3/sbe6/config/breezeexceptiondialog.cpp:27:
/home/jsardid/Documents/al3/sbe6/config/breezedetectwidget.h:34:10: fatal error: ui_breezedetectwidget.h: El fitxer o directori no existeix
   34 | #include "ui_breezedetectwidget.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/build.make:173: config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/breezeexceptiondialog.cpp.o] Error 1
In file included from /home/jsardid/Documents/al3/sbe6/build/config/kcm_sierrabreezeenhanceddecoration_autogen/EWIEGA46WW/moc_breezedetectwidget.cpp:9,
                 from /home/jsardid/Documents/al3/sbe6/build/config/kcm_sierrabreezeenhanceddecoration_autogen/mocs_compilation.cpp:3:
/home/jsardid/Documents/al3/sbe6/build/config/kcm_sierrabreezeenhanceddecoration_autogen/EWIEGA46WW/../../../../config/breezedetectwidget.h:34:10: fatal error: ui_breezedetectwidget.h: El fitxer o directori no existeix
   34 | #include "ui_breezedetectwidget.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/build.make:103: config/CMakeFiles/kcm_sierrabreezeenhanceddecoration.dir/kcm_sierrabreezeenhanceddecoration_autogen/mocs_compilation.cpp.o] Error 1
```

**Comment by kupiqu** [comment]
Other than that it works, many thanks @chiyuki0325

**Comment by kupiqu** [comment]
One thing that does not seem to work are window specific substitutions

**Comment by chiyuki0325** [comment]
The build issue should have been fixed. As for the window-specific subsitutions not working being caused by the API changes brought by KWin 6, I know nothing about C++ and just ported this by referring to [this commit](https://github.com/xynnylol/BreezeEnhanced-KDE6/commit/af8c8bca7473d4710b7caf311783061d7c18bd7a), so I can't fix it. 😮‍💨
Anyway, let's keep this PR open to give people using Plasma 6 a way to get SBE to work partially XD

**Comment by kupiqu** [comment]
Thanks for the work. I think this should be the reference to port SBE properly (based on Breeze Enhanced): [Commit of reference](https://github.com/xynnylol/BreezeEnhanced-KDE6/commit/b3de58529be2a671414b44f318993dbd34fd1eda)

**Comment by A1ca7raz** [comment]
See https://github.com/kupiqu/SierraBreezeEnhanced/pull/125

I made my patch, and it works fine.
https://github.com/A1ca7raz/nurpkgs/blob/main/pkgs/uncategorized/sierra-breeze-enhanced-kde6/fix-wayland.patch

**Comment by chiyuki0325** [comment]
Thanks to A1ca7raz for the patch.
Now that it has been merged, everything on Wayland should work correctly.
This patch also fixes an issue where rounded corners would be incorrectly drawn at the bottom corner of the title bar. SBE should now work fully in Plasma 6. 🎉

**Comment by chiyuki0325** [comment]
There's just one thing left to make this branch perfect: the README. I don't use another distributions, so I can't update the dependencies in the "Installation" section of the README to Qt 6. 🤔

**Comment by kupiqu** [comment]
Great work, thank you all!

**Pull request merged**
