### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by trmdi**

### CODE REVIEW

**Comment by kupiqu** [comment]
Actually there is no need to leave the session, can you please replace that section by just executing `kwin --replace` in krunner?

**Comment by trmdi** [comment]
In X11 it is `kwin_x11 --replace`. Do you know what it is in Wayland? `kwin_wayland --replace` ? I'm not sure.

**Comment by kupiqu** [comment]
> In X11 it is `kwin_x11 --replace`. Do you know what it is in Wayland? `kwin_wayland --replace` ? I'm not sure.

I think kwin is intelligent enough to apply the proper one, I have both installed and at least in X11 I do `kwin --replace` and works just fine

**Comment by kupiqu** [comment]
In any case, you're right, if you want to be explicit (I don't think we need to), it should be kwin_wayland

**Comment by trmdi** [comment]
My distro does not have the `kwin` command.
Finally, you should edit that line as you want then merge it. :)

**Comment by kupiqu** [comment]
> My distro does not have the `kwin` command.
> Finally, you should edit that line as you want then merge it. :)

I see, I frankly didn't know

**Comment by kupiqu** [comment]
thank you, README looks much better now

**Pull request merged**
