### PR TITLE
[macOS] Display all button symbols when hovering on any one.

### PR DESCRIPTION
**Pull request by trmdi**
Implement #43

### CODE REVIEW

**Comment by trmdi** [comment]
But it still doesn't work as expected with `applet-window-buttons`.
Do you know why? @kupiqu @psifidotos

**Comment by trmdi** [comment]
Ah, IIRC `applet-window-buttons` creates different decoration for each button, right?

**Comment by psifidotos** [comment]
yep, window buttons applet is creating a different decoration for each button the code part can be observed at: https://github.com/psifidotos/applet-window-buttons/blob/master/libappletdecoration/previewbutton.cpp#L301

I cant recall why I had ended in that, either I could not make it to work correctly OR I found it to work correctly that way and I didnt give it any more thought.

If someone wants to try to play with this, I think the best approach would be:

1. create a new class that will be qml capable just like PreviewBridge, we could name it, ButtonsStore. Its responsibility will be to register PreviewButtons in one single instance decoration and unregister them accordingly...
2. Whenever a button needs any decoration function e.g. reinitialization/signaling etc... it will call ButtonsStore instead of calling directly the decoration

You can **open a feature request for this at window buttons applet**, I could try to ckeck it out in the future but I dont know when, I dont have much time this period.

**Comment by trmdi** [comment]
@psifidotos 
Done: https://github.com/psifidotos/applet-window-buttons/issues/63

**Comment by kupiqu** [comment]
Thanks for the contribution. Unfortunately I found it unreliable when moving (hovering) from one button to another, sometimes it works as expected (all symbols shown), sometimes only the hovered symbol is shown.

Aslo, I would like this to be applied to all themes :)

**Comment by trmdi** [comment]
Uhm, there is something could be improved. :)

**Comment by trmdi** [comment]
> I found it unreliable when moving (hovering) from one button to another, sometimes it works as expected (all symbols shown), sometimes only the hovered symbol is shown.

Can you test this again? @kupiqu

**Comment by kupiqu** [comment]
I have to say that it works much better now. However, although rarely, it still fails to be consistent all the time. It's not obvious to me, what makes it fail.

**Comment by trmdi** [comment]
Can you post a video? It works very well here.

**Comment by kupiqu** [comment]
> Can you post a video? It works very well here.

To reproduce it, please try to go back and forth several times moving between buttons (It took me a while to observe the dissonance). It may be dependent on animations, but I'm not sure.

If still doing that way, you cannot reproduce, let me know and I will make and share a video tomorrow.

**Comment by trmdi** [comment]
Yes, please post your video. I can't reproduce any thing.

ezgif com-video-to-gif(3) ezgif com-video-to-gif(4)

**Comment by kupiqu** [comment]
Please see:

output

**Comment by kupiqu** [comment]
It doesn't work perfectly, at least in my system, but I decided to merge it and move from there. 

@trmdi further help in polishing it would be highly appreciated.

In the meantime, I will apply it to other themes and create an option for it.

Thanks @trmdi for your contribution!

**Comment by trmdi** [comment]
@psifidotos;

Do you know why? (please see kupiqu's screenshot above)

**Comment by psifidotos** [comment]
sorry no idea

**Pull request merged**
